# Generated by Django 6.0.1 on 2026-01-28 14:11

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_email'),
    ]

    operations = [
        VectorExtension(),
    ]
