# Generated by Django 6.0.1 on 2026-01-28 14:12

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_enable_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_embedding",
            field=VectorField(dimensions=768, null=True, blank=True),
        ),
    ]