# Generated by Django 6.0.1 on 2026-02-01 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_gender_customuser_interested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_distance',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
