# Generated by Django 6.0.1 on 2026-02-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_max_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_distance',
            field=models.IntegerField(default=20),
        ),
    ]
