# Generated by Django 6.0.1 on 2026-02-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_max_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_age_diff',
            field=models.IntegerField(default=5),
        ),
    ]
